[build-system]
requires = ["setuptools >= 61.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "dqn-algorithms"
version = "1.0"
dependencies = ["torch", "numpy"]
license = {text = "MIT"}